version: '3'

services:
  php:
    image: "php:7.4-cli"
    volumes:
    - ./:/var/www/html
    env_file:
      fruits.env
    environment: # these variables can be accessible from the app (index.php)
      FRUITS: "${FRUITS} cherry peach" # here FRUITS from fruits.env is being overriden, ${FRUITS} comes from the shell FRUITS=raspberry docker-compose up
      COLORS: ${BANANA_COLOR}
    networks:
      - fruit_network
    working_dir: /var/www/html
    entrypoint: 'php index.php'

networks:
  fruit_network: ~
