version: "3"

services:
  nginx:
    image: nginx:latest
    ports:
      - "8003:80"
    volumes:
      - ./:/app
      - ./docker/nginx/site-3.conf:/etc/nginx/conf.d/default.conf
  php:
    image: php:7-fpm
    volumes:
      - .:/app
