# Step 1: nginx
version: "3"

services:
    web:
        image: nginx:latest
        ports:
            - "8003:80"
        volumes:
            - ./:/app
            - ./docker/nginx/site-2.conf:/etc/nginx/conf.d/default.conf