version: '3'
services:
    composer:
        image: composer:1.9.3
        environment: 
            - COMPOSER_CACHE_DIR=/app/var/cache/composer # Composer local cache directory
        volumes:
            - .:/app
        restart: never
    php:
        image: php:7.4-cli
        restart: never
        volumes:
            - .:/app
        working_dir: /app # Pour que /app doit le dossier courant lorsqu'on lance docker-compose run php
    phpunit:
        image: php:7.4-cli
        restart: never
        volumes:
            - .:/app
        working_dir: /app
        entrypoint: ["php", "vendor/bin/phpunit"] # Commande qui s'exécute quand on lance le conteneur.
    nginx:
        image: nginx:1.17.8-alpine
        ports:
            - 8080:80 # Expose le port local 8080 correspondant au port 80 du conteneur
        volumes:
            - .:/app
            - ./var/log/nginx:/var/log/nginx
            - .conf/nginx/site.conf:/etc/nginx/conf.d/default.conf