cloneAndCompose: clone compose
	echo "done!"

clone:
	git clone https://github.com/OpenClassrooms-Student-Center/ghost-cms.git

compose:
	docker-compose up

stopAndRemove: stop remove
	echo "done!"

stop:
	docker-compose stop

remove:
	docker-compose down
